### ISSUE TITLE
user testing

### ISSUE THREAD

**Issue by nickpovey** [FAC-11/AllAboutMe#107]
Here is the feedback from my colleagues at the anna freud centre

- [ ] Ability to hide questions #117 
- [ ] Add open section to just write whatever you want #119 
- [x] Generated email of form answers should get sent to your email as well #120
- [x] Home button icon looks like a bar chart and is not clearly a home button, replace with icon of a house #124 
- [ ] The rain prompt shows up for all questions, and hence doesn't make sense for some of them #138 
- [ ] Didn't like the background picture, replace/ability to put your own one there (tried to get them to suggest an alternative, no luck) #137 
- [ ] Not very child friendly, add happy/smiley faces instead of yes/no or maybe have an alternative version of the app that would have this that you could choose, selecting your age range at the beginning #136 

Some things I have noticed

- [x]  Question 6.Re phrase to "What helps you to keep well?" #116
- [x] There isn't a back button on the your progress page and the colour section page, so some times people kept on pressing the back button on the actual web browser on my tablet which would take them back to github, I don't think it would hurt to just have it everywhere if possible. #118
