### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by polyccon** [FAC-11/AllAboutMe#162]
General accessibility could be improved for our app starting with the following issues:
- [x] #147 pressing enter on signup page doesnt submit
- [x] #159 text is hard to read in some places
- [x] #164 not all form inputs have labels
