### ISSUE TITLE
Responsiveness 

### ISSUE THREAD

**Issue by polyccon** [FAC-11/AllAboutMe#171]
- [x] #188 login page on mobile
- [x] #140 Finish page on mobile version
- [x] #146 Send page on mobile
